### ISSUE TITLE
Can not make it

### ISSUE THREAD

**Issue by ManagedMango** [Falkirks/SimplePortals#6]
I cannot make a portal I have the right plug-in simple warp and all it says is it is an invalid warp what do I need to do
![screenshot_2015-12-18-17-05-52](https://cloud.githubusercontent.com/assets/16353509/11902447/da0811a8-a5a9-11e5-9cb8-60b36725a954.png)
![screenshot_2015-12-18-17-07-09](https://cloud.githubusercontent.com/assets/16353509/11902451/e7b6666a-a5a9-11e5-8a33-ff7bef93d8f3.png)
![screenshot_2015-12-18-17-07-13](https://cloud.githubusercontent.com/assets/16353509/11902452/ee74508e-a5a9-11e5-9ff2-eeae7b46973c.png)

**Comment by falkirks** [comment]
You need to make a warp in SimpleWarp first with the command `/addwarp`
